# See https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/azure-iot-edge?view=azure-devops
pool:
    vmImage: 'ubuntu-latest'

variables:
    registryName: watchdogcr
    azureContainerRegistry: watchdogcr.azurecr.io
    iothubname: watchdog-iot-hub
    deviceId: mySimDevice
    resourceGroupName: iot-watchdog-demo

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'pip install -U iotedgedev'

- task: AzureIoTEdge@2
  displayName: AzureIoTEdge - Build module images
  inputs:
    action: Build module images
    templateFilePath: $(Build.SourcesDirectory)/edge/SimulatedEdgeDevice/deployment.template.json
    defaultPlatform: amd64

- task: AzureIoTEdge@2
  displayName: AzureIoTEdge - Push module images
  inputs:
    action: Push module images
    containerregistrytype: Azure Container Registry
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: '{"loginServer":"$(azureContainerRegistry)", "id" : "/subscriptions/${subscriptionId}/resourceGroups/${resourceGroupName}/providers/Microsoft.ContainerRegistry/registries/${registryName}"}'
    templateFilePath: $(Build.SourcesDirectory)/edge/SimulatedEdgeDevice/deployment.template.json
    defaultPlatform: amd64

- task: AzureIoTEdge@2
  displayName: 'Azure IoT Edge - Deploy to IoT Edge devices'
  inputs:
    action: 'Deploy to IoT Edge devices'
    deploymentFilePath: $(Build.SourcesDirectory)/edge/SimulatedEdgeDevice/deployment.template.json
    azureSubscription: $(azureSubscriptionEndpoint)
    iothubname: $(iothubname)
    deviceOption: 'Single Device'
    deviceId: $(deviceId)