// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: HeartbeatMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HeartbeatProto {

  /// <summary>Holder for reflection information generated from HeartbeatMessage.proto</summary>
  public static partial class HeartbeatMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for HeartbeatMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HeartbeatMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZIZWFydGJlYXRNZXNzYWdlLnByb3RvEg5IZWFydGJlYXRQcm90byLSAgoQ",
            "SGVhcnRiZWF0TWVzc2FnZRIPCgdNc2dUeXBlGAEgASgJEhAKCERldmljZUlk",
            "GAIgASgJEhAKCE1vZHVsZUlkGAMgASgJEgoKAklkGAQgASgDEiAKGEhlYXJ0",
            "YmVhdENyZWF0ZWRUaWNrc1V0YxgFIAEoAxIMCgRTZW50GAYgASgJEhEKCUVm",
            "ZmVjdGl2ZRgHIAEoCRINCgVPbnNldBgIIAEoCRIPCgdFeHBpcmVzGAkgASgJ",
            "EgwKBEVuZHMYCiABKAkSDgoGU3RhdHVzGAsgASgJEhAKCENhdGVnb3J5GAwg",
            "ASgJEhAKCFNldmVyaXR5GA0gASgJEhEKCUNlcnRhaW50eRgOIAEoCRIPCgdV",
            "cmdlbmN5GA8gASgJEg0KBUV2ZW50GBAgASgJEhAKCEhlYWRsaW5lGBEgASgJ",
            "EhMKC0luc3RydWN0aW9uGBIgASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::HeartbeatProto.HeartbeatMessage), global::HeartbeatProto.HeartbeatMessage.Parser, new[]{ "MsgType", "DeviceId", "ModuleId", "Id", "HeartbeatCreatedTicksUtc", "Sent", "Effective", "Onset", "Expires", "Ends", "Status", "Category", "Severity", "Certainty", "Urgency", "Event", "Headline", "Instruction" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class HeartbeatMessage : pb::IMessage<HeartbeatMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HeartbeatMessage> _parser = new pb::MessageParser<HeartbeatMessage>(() => new HeartbeatMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HeartbeatMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HeartbeatProto.HeartbeatMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HeartbeatMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HeartbeatMessage(HeartbeatMessage other) : this() {
      msgType_ = other.msgType_;
      deviceId_ = other.deviceId_;
      moduleId_ = other.moduleId_;
      id_ = other.id_;
      heartbeatCreatedTicksUtc_ = other.heartbeatCreatedTicksUtc_;
      sent_ = other.sent_;
      effective_ = other.effective_;
      onset_ = other.onset_;
      expires_ = other.expires_;
      ends_ = other.ends_;
      status_ = other.status_;
      category_ = other.category_;
      severity_ = other.severity_;
      certainty_ = other.certainty_;
      urgency_ = other.urgency_;
      event_ = other.event_;
      headline_ = other.headline_;
      instruction_ = other.instruction_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HeartbeatMessage Clone() {
      return new HeartbeatMessage(this);
    }

    /// <summary>Field number for the "MsgType" field.</summary>
    public const int MsgTypeFieldNumber = 1;
    private string msgType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MsgType {
      get { return msgType_; }
      set {
        msgType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DeviceId" field.</summary>
    public const int DeviceIdFieldNumber = 2;
    private string deviceId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DeviceId {
      get { return deviceId_; }
      set {
        deviceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ModuleId" field.</summary>
    public const int ModuleIdFieldNumber = 3;
    private string moduleId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ModuleId {
      get { return moduleId_; }
      set {
        moduleId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 4;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "HeartbeatCreatedTicksUtc" field.</summary>
    public const int HeartbeatCreatedTicksUtcFieldNumber = 5;
    private long heartbeatCreatedTicksUtc_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long HeartbeatCreatedTicksUtc {
      get { return heartbeatCreatedTicksUtc_; }
      set {
        heartbeatCreatedTicksUtc_ = value;
      }
    }

    /// <summary>Field number for the "Sent" field.</summary>
    public const int SentFieldNumber = 6;
    private string sent_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Sent {
      get { return sent_; }
      set {
        sent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Effective" field.</summary>
    public const int EffectiveFieldNumber = 7;
    private string effective_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Effective {
      get { return effective_; }
      set {
        effective_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Onset" field.</summary>
    public const int OnsetFieldNumber = 8;
    private string onset_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Onset {
      get { return onset_; }
      set {
        onset_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Expires" field.</summary>
    public const int ExpiresFieldNumber = 9;
    private string expires_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Expires {
      get { return expires_; }
      set {
        expires_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Ends" field.</summary>
    public const int EndsFieldNumber = 10;
    private string ends_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Ends {
      get { return ends_; }
      set {
        ends_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Status" field.</summary>
    public const int StatusFieldNumber = 11;
    private string status_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Status {
      get { return status_; }
      set {
        status_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Category" field.</summary>
    public const int CategoryFieldNumber = 12;
    private string category_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Category {
      get { return category_; }
      set {
        category_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Severity" field.</summary>
    public const int SeverityFieldNumber = 13;
    private string severity_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Severity {
      get { return severity_; }
      set {
        severity_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Certainty" field.</summary>
    public const int CertaintyFieldNumber = 14;
    private string certainty_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Certainty {
      get { return certainty_; }
      set {
        certainty_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Urgency" field.</summary>
    public const int UrgencyFieldNumber = 15;
    private string urgency_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Urgency {
      get { return urgency_; }
      set {
        urgency_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Event" field.</summary>
    public const int EventFieldNumber = 16;
    private string event_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Event {
      get { return event_; }
      set {
        event_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Headline" field.</summary>
    public const int HeadlineFieldNumber = 17;
    private string headline_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Headline {
      get { return headline_; }
      set {
        headline_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Instruction" field.</summary>
    public const int InstructionFieldNumber = 18;
    private string instruction_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Instruction {
      get { return instruction_; }
      set {
        instruction_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HeartbeatMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HeartbeatMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MsgType != other.MsgType) return false;
      if (DeviceId != other.DeviceId) return false;
      if (ModuleId != other.ModuleId) return false;
      if (Id != other.Id) return false;
      if (HeartbeatCreatedTicksUtc != other.HeartbeatCreatedTicksUtc) return false;
      if (Sent != other.Sent) return false;
      if (Effective != other.Effective) return false;
      if (Onset != other.Onset) return false;
      if (Expires != other.Expires) return false;
      if (Ends != other.Ends) return false;
      if (Status != other.Status) return false;
      if (Category != other.Category) return false;
      if (Severity != other.Severity) return false;
      if (Certainty != other.Certainty) return false;
      if (Urgency != other.Urgency) return false;
      if (Event != other.Event) return false;
      if (Headline != other.Headline) return false;
      if (Instruction != other.Instruction) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MsgType.Length != 0) hash ^= MsgType.GetHashCode();
      if (DeviceId.Length != 0) hash ^= DeviceId.GetHashCode();
      if (ModuleId.Length != 0) hash ^= ModuleId.GetHashCode();
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (HeartbeatCreatedTicksUtc != 0L) hash ^= HeartbeatCreatedTicksUtc.GetHashCode();
      if (Sent.Length != 0) hash ^= Sent.GetHashCode();
      if (Effective.Length != 0) hash ^= Effective.GetHashCode();
      if (Onset.Length != 0) hash ^= Onset.GetHashCode();
      if (Expires.Length != 0) hash ^= Expires.GetHashCode();
      if (Ends.Length != 0) hash ^= Ends.GetHashCode();
      if (Status.Length != 0) hash ^= Status.GetHashCode();
      if (Category.Length != 0) hash ^= Category.GetHashCode();
      if (Severity.Length != 0) hash ^= Severity.GetHashCode();
      if (Certainty.Length != 0) hash ^= Certainty.GetHashCode();
      if (Urgency.Length != 0) hash ^= Urgency.GetHashCode();
      if (Event.Length != 0) hash ^= Event.GetHashCode();
      if (Headline.Length != 0) hash ^= Headline.GetHashCode();
      if (Instruction.Length != 0) hash ^= Instruction.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MsgType.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MsgType);
      }
      if (DeviceId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DeviceId);
      }
      if (ModuleId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ModuleId);
      }
      if (Id != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Id);
      }
      if (HeartbeatCreatedTicksUtc != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(HeartbeatCreatedTicksUtc);
      }
      if (Sent.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Sent);
      }
      if (Effective.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Effective);
      }
      if (Onset.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Onset);
      }
      if (Expires.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Expires);
      }
      if (Ends.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Ends);
      }
      if (Status.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Status);
      }
      if (Category.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(Category);
      }
      if (Severity.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(Severity);
      }
      if (Certainty.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(Certainty);
      }
      if (Urgency.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(Urgency);
      }
      if (Event.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(Event);
      }
      if (Headline.Length != 0) {
        output.WriteRawTag(138, 1);
        output.WriteString(Headline);
      }
      if (Instruction.Length != 0) {
        output.WriteRawTag(146, 1);
        output.WriteString(Instruction);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MsgType.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MsgType);
      }
      if (DeviceId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DeviceId);
      }
      if (ModuleId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ModuleId);
      }
      if (Id != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Id);
      }
      if (HeartbeatCreatedTicksUtc != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(HeartbeatCreatedTicksUtc);
      }
      if (Sent.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Sent);
      }
      if (Effective.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Effective);
      }
      if (Onset.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Onset);
      }
      if (Expires.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Expires);
      }
      if (Ends.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Ends);
      }
      if (Status.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Status);
      }
      if (Category.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(Category);
      }
      if (Severity.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(Severity);
      }
      if (Certainty.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(Certainty);
      }
      if (Urgency.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(Urgency);
      }
      if (Event.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(Event);
      }
      if (Headline.Length != 0) {
        output.WriteRawTag(138, 1);
        output.WriteString(Headline);
      }
      if (Instruction.Length != 0) {
        output.WriteRawTag(146, 1);
        output.WriteString(Instruction);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MsgType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MsgType);
      }
      if (DeviceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceId);
      }
      if (ModuleId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ModuleId);
      }
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (HeartbeatCreatedTicksUtc != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(HeartbeatCreatedTicksUtc);
      }
      if (Sent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Sent);
      }
      if (Effective.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Effective);
      }
      if (Onset.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Onset);
      }
      if (Expires.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Expires);
      }
      if (Ends.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ends);
      }
      if (Status.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Status);
      }
      if (Category.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Category);
      }
      if (Severity.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Severity);
      }
      if (Certainty.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Certainty);
      }
      if (Urgency.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Urgency);
      }
      if (Event.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Event);
      }
      if (Headline.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Headline);
      }
      if (Instruction.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Instruction);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HeartbeatMessage other) {
      if (other == null) {
        return;
      }
      if (other.MsgType.Length != 0) {
        MsgType = other.MsgType;
      }
      if (other.DeviceId.Length != 0) {
        DeviceId = other.DeviceId;
      }
      if (other.ModuleId.Length != 0) {
        ModuleId = other.ModuleId;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.HeartbeatCreatedTicksUtc != 0L) {
        HeartbeatCreatedTicksUtc = other.HeartbeatCreatedTicksUtc;
      }
      if (other.Sent.Length != 0) {
        Sent = other.Sent;
      }
      if (other.Effective.Length != 0) {
        Effective = other.Effective;
      }
      if (other.Onset.Length != 0) {
        Onset = other.Onset;
      }
      if (other.Expires.Length != 0) {
        Expires = other.Expires;
      }
      if (other.Ends.Length != 0) {
        Ends = other.Ends;
      }
      if (other.Status.Length != 0) {
        Status = other.Status;
      }
      if (other.Category.Length != 0) {
        Category = other.Category;
      }
      if (other.Severity.Length != 0) {
        Severity = other.Severity;
      }
      if (other.Certainty.Length != 0) {
        Certainty = other.Certainty;
      }
      if (other.Urgency.Length != 0) {
        Urgency = other.Urgency;
      }
      if (other.Event.Length != 0) {
        Event = other.Event;
      }
      if (other.Headline.Length != 0) {
        Headline = other.Headline;
      }
      if (other.Instruction.Length != 0) {
        Instruction = other.Instruction;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MsgType = input.ReadString();
            break;
          }
          case 18: {
            DeviceId = input.ReadString();
            break;
          }
          case 26: {
            ModuleId = input.ReadString();
            break;
          }
          case 32: {
            Id = input.ReadInt64();
            break;
          }
          case 40: {
            HeartbeatCreatedTicksUtc = input.ReadInt64();
            break;
          }
          case 50: {
            Sent = input.ReadString();
            break;
          }
          case 58: {
            Effective = input.ReadString();
            break;
          }
          case 66: {
            Onset = input.ReadString();
            break;
          }
          case 74: {
            Expires = input.ReadString();
            break;
          }
          case 82: {
            Ends = input.ReadString();
            break;
          }
          case 90: {
            Status = input.ReadString();
            break;
          }
          case 98: {
            Category = input.ReadString();
            break;
          }
          case 106: {
            Severity = input.ReadString();
            break;
          }
          case 114: {
            Certainty = input.ReadString();
            break;
          }
          case 122: {
            Urgency = input.ReadString();
            break;
          }
          case 130: {
            Event = input.ReadString();
            break;
          }
          case 138: {
            Headline = input.ReadString();
            break;
          }
          case 146: {
            Instruction = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            MsgType = input.ReadString();
            break;
          }
          case 18: {
            DeviceId = input.ReadString();
            break;
          }
          case 26: {
            ModuleId = input.ReadString();
            break;
          }
          case 32: {
            Id = input.ReadInt64();
            break;
          }
          case 40: {
            HeartbeatCreatedTicksUtc = input.ReadInt64();
            break;
          }
          case 50: {
            Sent = input.ReadString();
            break;
          }
          case 58: {
            Effective = input.ReadString();
            break;
          }
          case 66: {
            Onset = input.ReadString();
            break;
          }
          case 74: {
            Expires = input.ReadString();
            break;
          }
          case 82: {
            Ends = input.ReadString();
            break;
          }
          case 90: {
            Status = input.ReadString();
            break;
          }
          case 98: {
            Category = input.ReadString();
            break;
          }
          case 106: {
            Severity = input.ReadString();
            break;
          }
          case 114: {
            Certainty = input.ReadString();
            break;
          }
          case 122: {
            Urgency = input.ReadString();
            break;
          }
          case 130: {
            Event = input.ReadString();
            break;
          }
          case 138: {
            Headline = input.ReadString();
            break;
          }
          case 146: {
            Instruction = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
