# This is a basic workflow to help you get started with Actions

name: Deploy Power Platform Solution 

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  release:
    types: [created]

jobs:
  convert-to-managed:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    
    - name: Export solution as managed
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://tornadoalley.crm.dynamics.com/'
        user-name: ${{ secrets.MYUSERNAME }}
        password-secret: ${{ secrets.MYPASSWORD }}
        managed: true
        solution-name: 'TornadoAlerts-prod'
        solution-output-file: 'solutions/ship/TornadoAlerts-prod.zip'

    - name: Publish Solution
      uses: microsoft/powerplatform-actions/publish-solution@v0
      with:
        environment-url: 'https://reddog.crm.dynamics.com'
        solution-file: 'solutions/ship/TornadoAlerts-prod.zip'
        user-name: ${{ secrets.MYUSERNAME }}
        password-secret: ${{ secrets.MYPASSWORD }}
        force-overwrite: true
        publish-changes: true
