# This is a basic workflow to help you get started with Actions

name: Deploy Power Platform Solution 

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  release:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Publish Solution
        uses: microsoft/powerplatform-actions/publish-solution@v0
        with:
          environment-url: 'https://reddog.crm.dynamics.com'
          solution-file: 'solutions/TornadoAlerts.zip'
          user-name: ${{ secrets.MYUSERNAME }}
          password-secret: ${{ secrets.MYPASSWORD }}
          force-overwrite: true
          publish-changes: true
